[project]
name = "mini-pytorch-clone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "mypy>=1.15.0",
    "numpy>=2.2.4",
    "pytest>=8.3.5",
]
